import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header"; // مسار الهيدر
import Footer from "@/components/Footer"; // استدعاء الفوتر الجديد هنا

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ar" className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}>
      <body className="min-h-full flex flex-col bg-white">
        {/* الهيدر يظهر في كل الموقع */}
        <Header /> 
        
        {/* محتوى الصفحات المتغير (يأخذ المساحة المتبقية بالكامل) */}
        <main className="flex-1 w-full">
          {children}
        </main>

        {/* الفوتر يظهر أسفل كل الموقع */}
        <Footer />
      </body>
    </html>
  );
}